### ISSUE TITLE
Migrations & Models folders

### ISSUE THREAD

**Issue by woodrdk** [woodrdk/CarRepairTracker#13]

**Comment by AnMcCbusiness** [comment]
PM> Enable-Migrations
Checking if the context targets an existing database...
Code First Migrations enabled for project AnthonyECommerce.
PM> Add-Migration "Added Product"
Scaffolding migration 'Added Product'.
The Designer Code for this migration file includes a snapshot of your current Code First model. This snapshot is used to calculate the changes to your model when you scaffold the next migration. If you make additional changes to your model that you want to include in this migration, then you can re-scaffold it by running 'Add-Migration Added Product' again.
PM> Update-Database
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201807191750255_Added Product].
Applying explicit migration: 201807191750255_Added Product.
Running Seed method.
PM>

**Comment by AnMcCbusiness** [comment]
Having issues with getting the database to pop up. The current code is in ModelsAndMigrations branch at the moment.

**Comment by AnMcCbusiness** [comment]
Found fix with an updated version of SQL Server Express because of some Bug Fixes I needed.
